version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network

  customer:
    build: ./customer
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network

  sale:
    build: ./sale
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network

  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - customer
      - sale
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge 